change password configuration in the properties file
openmrs/openmrs-module-authentication pull request #13
Opened 2024-06-26 15:31 UTC by gitcliff

PR is adding the ability to set require password change on first login via the openmrs runtime properties

2024-06-26 15:57 UTC, ibacher requested changes
Thanks @gitcliff! This is a reasonable first-pass, but see my comments. Also we should definitely have a ticket in the Authentication module Jira project for this. Could you please create one? I can fill in details.

2024-06-26 15:57 UTC, ibacher commented on omod/src/main/java/org/openmrs/module/authentication/web/AuthenticationFilter.java
> +                            }
Fix the indentation here...

2024-06-26 15:57 UTC, ibacher commented on omod/src/test/java/org/openmrs/module/authentication/web/AuthenticationFilterTest.java
> +        // Verify redirection to password change URL
Indentation

2024-06-26 15:57 UTC, ibacher commented on api/src/main/java/org/openmrs/module/authentication/AuthenticationConfig.java
> +    public static boolean isPasswordChangeOnFirstLoginRequired() {
Isn't this covered by `getBoolean()` below?

2024-06-26 15:57 UTC, ibacher commented on omod/src/main/java/org/openmrs/module/authentication/web/AuthenticationFilter.java
> +                                  response.sendRedirect(passwordChangeUrl);
So the page to redirect to _must_ be configurable. I would also plug this code into the `determineSuccessRedirectUrl()` function, so we only have a single part of code actually emitting a redirect.

2024-06-26 15:57 UTC, ibacher commented on api/src/main/java/org/openmrs/module/authentication/UserLogin.java
> +    }
I don't see why we need these? The only thing we _should_ be checking is whether the _user_ has the user property `OpenmrsConstants.USER_PROPERTY_CHANGE_PASSWORD` set to "true". That way we support both first login and additional password reset changes.

2024-06-26 21:08 UTC, gitcliff commented
> Thanks @gitcliff! This is a reasonable first-pass, but see my comments. Also we should definitely have a ticket in the Authentication module Jira project for this. Could you please create one? I can fill in details.
thanks @ibacher for the review ,,,i have addressed the comments ..
I don't see the [JIRA board for this module ](https://openmrs.atlassian.net/jira/projects?page=1&sortKey=name&sortOrder=ASC) to file a ticket , should i create one ?

2024-06-28 17:19 UTC, ibacher commented
Created one here: https://openmrs.atlassian.net/jira/software/projects/AUT/

2024-06-28 17:20 UTC, ibacher commented on api/src/main/java/org/openmrs/module/authentication/AuthenticationConfig.java
> +    public static final String REQUIRE_PASSWORD_CHANGE_ON_FIRST_LOGIN = "authentication.requirePasswordChangeOnFirstLogin";
Let's rename this to `SUPPORT_FORCED_PASSWORD_CHANGE`

2024-06-28 17:20 UTC, ibacher commented on omod/src/main/java/org/openmrs/module/authentication/web/AuthenticationFilter.java
> +		}
This actually needs to come _before_ the normal redirect processing

2024-07-02 08:25 UTC, gitcliff commented on omod/src/main/java/org/openmrs/module/authentication/web/AuthenticationFilter.java
> +		}
thanks @ibacher ,,,
kindly review

2024-07-02 11:46 UTC, mseaton commented on omod/src/main/java/org/openmrs/module/authentication/web/AuthenticationFilter.java
> +		}
@gitcliff I wouldn't think that this is something that we are just aiming to do once, as soon as the user is authenticated, and only then.  For example, if they authenticate, and we redirect them to this page, and then they just choose to enter a different url into the address bar, this wouldn't prevent them from doing that.  My assumption is that we want to force them to change their password without accessing any other pages.  So, this is really something we want to do independently of authentication.  I would think this could either be achieved via a separate servlet filter that runs after the AuthenticationFilter, or a separate check in the AuthenticationFilter that is placed at the end (eg. the code that is hit if the user is already authenticated).  Interested in @ibacher 's thoughts...

2024-07-02 11:48 UTC, mseaton commented on omod/src/main/java/org/openmrs/module/authentication/web/AuthenticationFilter.java
> +				"true".equals(OpenmrsConstants.USER_PROPERTY_CHANGE_PASSWORD)) {
This is not actually checking the user property value, but is checking the value of the constant.  You actually need to fetch the user property value with this name, not just compare the constant itself.

2024-07-02 11:58 UTC, ibacher commented on omod/src/main/java/org/openmrs/module/authentication/web/AuthenticationFilter.java
> +		}
Hmmmm... That's actually a good point. Maybe having this as a second filter makes the most sense. There will need to be some additional configuration around this too... I.e., we need to white-list certain URLs (e.g., to allow the user to hit the "change password" endpoint).

2024-07-02 14:52 UTC, gitcliff commented on omod/src/main/java/org/openmrs/module/authentication/web/AuthenticationFilter.java
> +		}
thanks @ibacher  and @mseaton

2024-07-10 12:12 UTC, mseaton requested changes

2024-07-10 12:12 UTC, mseaton commented on api/src/main/java/org/openmrs/module/authentication/AuthenticationConfig.java
> +    public static final String PASS_WORD_CHANGE_WHITE_LIST = "authentication.passWordChangeWhiteList";
`PASS_WORD` -> `PASSWORD`, and `passWord` -> `password`

2024-07-10 12:12 UTC, mseaton commented on api/src/main/java/org/openmrs/module/authentication/AuthenticationConfig.java
> +        return getConfig().getProperty(PASSWORD_CHANGE_URL, "/changePassword");
Does this refer to an actual /changePassword page somewhere?  If we are going to have a default, we should make sure it actually works under some standard conditions (eg. with legacyui running)

2024-07-10 12:12 UTC, mseaton commented on omod/src/main/java/org/openmrs/module/authentication/web/ForcePasswordChangeFilter.java
> + * the user to change his password.
Why just a *.html and *.form?  I don't think this comment is accurate, is it?

2024-07-10 12:12 UTC, mseaton commented on omod/src/main/java/org/openmrs/module/authentication/web/ForcePasswordChangeFilter.java
> +	private String changePasswordForm;
This doesn't seem right.  Why do you have this here?  Aren't you getting this from the AuthenticationConfig, which is able to be specified at runtime, not a hard-coded filter param?  Remove this.

2024-07-10 14:40 UTC, gitcliff commented on omod/src/main/java/org/openmrs/module/authentication/web/ForcePasswordChangeFilter.java
> + * the user to change his password.
thanks  @mseaton
 had skipped removing it but removed now

2024-07-11 16:45 UTC, mseaton commented on omod/src/main/java/org/openmrs/module/authentication/web/AuthenticationFilter.java
> +		    AuthenticationConfig.getBoolean(OpenmrsConstants.USER_PROPERTY_CHANGE_PASSWORD, false)) {
This is not correct.  The USER_PROPERTY_CHANGE_PASSWORD is not coming from the AuthenticationConfig, but from the user properties.

2024-07-11 16:47 UTC, mseaton commented on omod/src/main/java/org/openmrs/module/authentication/web/AuthenticationFilter.java
> +		    AuthenticationConfig.getBoolean(OpenmrsConstants.USER_PROPERTY_CHANGE_PASSWORD, false)) {
Actually, sorry - this entire set of changes should not be here at all.  This is now covered by the other filter.  You need to remove these changes to this method.

2024-07-11 16:49 UTC, mseaton commented on omod/src/main/java/org/openmrs/module/authentication/web/ForcePasswordChangeFilter.java
> +				.get(OpenmrsConstants.USER_PROPERTY_CHANGE_PASSWORD);
You should be able to use `userLogin.getUser().getUserProperty(OpenmrsConstants.USER_PROPERTY_CHANGE_PASSWORD)`

2024-07-11 16:51 UTC, mseaton commented on omod/src/main/java/org/openmrs/module/authentication/web/ForcePasswordChangeFilter.java
> +
Previously, you had a check for `(AuthenticationConfig.getBoolean(AuthenticationConfig.SUPPORT_FORCED_PASSWORD_CHANGE, false)`.  Are you no longer supporting this?  I would expect to see that in this filter.  And I'd also recommend checking this once and saving it so that you can make this filter as efficient as possible for every request.

2024-07-11 16:54 UTC, mseaton commented on omod/src/main/java/org/openmrs/module/authentication/web/ForcePasswordChangeFilter.java
> +		Boolean changePasswordFlag = AuthenticationConfig.getBoolean(changePasswordProperty, false);
This is not correct.  You don't use the AuthenticationConfig to do this, you would use something like `BooleanUtils.isTrue()`

2024-07-11 16:55 UTC, mseaton commented on omod/src/main/java/org/openmrs/module/authentication/web/ForcePasswordChangeFilter.java
> +			String changePasswordUrl = AuthenticationConfig.getChangePasswordUrl();
This seems like something that should be evaluated once and cached, not evaluated and checked per request.

2024-07-11 19:23 UTC, gitcliff commented on omod/src/main/java/org/openmrs/module/authentication/web/ForcePasswordChangeFilter.java
> +
thanks @mseaton 
i have added the check and cached it

2024-07-11 21:21 UTC, mseaton requested changes
Looking better.  Please re-request review via the github PR tools when you are ready for this to be looked at again.

2024-07-11 21:21 UTC, mseaton commented on api/src/main/java/org/openmrs/module/authentication/AuthenticationConfig.java
> +
Remove this newline

2024-07-11 21:21 UTC, mseaton commented on omod/src/main/java/org/openmrs/module/authentication/web/ForcePasswordChangeFilter.java
> +		this.supportForcedPasswordChange = BooleanUtils.isTrue(AuthenticationConfig.getBoolean
The BooleanUtils.isTrue here is unnecessary.  Just use the AuthenticationConfig method

2024-07-11 21:21 UTC, mseaton commented on omod/src/main/java/org/openmrs/module/authentication/web/ForcePasswordChangeFilter.java
> +		    || !supportForcedPasswordChange) {
I would evaluate `supportForcedPasswordChange` first, as it is faster and if it is true then it won't bother evaluating the next.  Why aren't you also caching the whitelist value at startup?

2024-07-11 21:21 UTC, mseaton commented on omod/src/main/java/org/openmrs/module/authentication/web/ForcePasswordChangeFilter.java
> +	  HttpServletResponse response) {
Ugly

2024-07-15 11:51 UTC, gitcliff commented on omod/src/main/java/org/openmrs/module/authentication/web/ForcePasswordChangeFilter.java
> +		    || !supportForcedPasswordChange) {
yeah, thanks @mseaton ,, cached the whitelist value at startup

2024-07-15 18:00 UTC, gitcliff commented on omod/src/main/java/org/openmrs/module/authentication/web/ForcePasswordChangeFilter.java
> +		Boolean changePasswordFlag = BooleanUtils.isTrue(Boolean.valueOf(changePasswordProperty));
thanks @ibacher fixed it

2024-07-15 19:16 UTC, ibacher commented on omod/src/main/java/org/openmrs/module/authentication/web/ForcePasswordChangeFilter.java
>  		if (userLogin.isUserAuthenticated() && BooleanUtils.isTrue(changePasswordFlag)) {
So, as I noted, you can get rid of the `BooleanUtils.isTrue()` call on this line too.

2024-07-15 19:17 UTC, ibacher approved these changes

2024-07-16 12:10 UTC, mseaton approved these changes

2024-07-16 12:16 UTC, merged